In [10]:
import pandas as pd
from os.path import join

In [11]:
date_export = "2024-07-28"
date_export2 = date_export.replace("-", "")
data_file = join("extractions", f"rbx_vdg_{date_export2}.csv.gz")

rbx_vdg = pd.read_csv(data_file)

/tmp/ipykernel_15427/531749889.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  rbx_vdg = pd.read_csv(data_file)

In [12]:
rbx_vdg

,record_id,alignement_bnf,rbx_date_creation_notice,rbx_vdg_action,rbx_vdg_date,rbx_support,agence_cat,pat
0,1,True,2014-06-30,notice bibliographique et autorités,20240721.0,Livre,BnF,False
1,2,True,2014-06-30,notice bibliographique et autorités,20240721.0,Livre,BnF,False
2,3,True,2014-06-30,notice bibliographique et autorités,20240721.0,Livre,BnF,False
3,4,True,2014-06-30,notice bibliographique et autorités,20240721.0,Livre,BnF,False
4,6,True,2014-06-30,notice bibliographique et autorités,20240721.0,Livre,BnF,False
...,...,...,...,...,...,...,...,...
237616,368068,False,2024-07-27,notice bibliographique et autorités,20240728.0,Livre,Electre,False
237617,368070,True,2024-07-27,notice bibliographique et autorités,20240728.0,Livre,BnF,False
237618,368071,True,2024-07-27,notice bibliographique et autorités,20240728.0,Livre,BnF,False
237619,368072,True,2024-07-27,notice bibliographique et autorités,20240728.0,Livre,BnF,False
237620,368073,True,2024-07-27,notice bibliographique et autorités,20240728.0,Livre,BnF,False

In [13]:
rbx_vdg.groupby('alignement_bnf')['record_id'].count()

alignement_bnf
False    109791
True     127830
Name: record_id, dtype: int64

In [18]:
rbx_vdg.groupby('agence_cat')['record_id'].count().reset_index().sort_values(by='record_id', ascending=False)

               agence_cat  record_id
1                     BnF     116894
6  Médiathèque de Roubaix      95408
4                 Electre       9091
3                  COLACO       4469
2                  CDMAIL       4394
5                     GAM       3600
0                    ADAV       2691
7                   autre       1029